# Generated by Django 4.2.13 on 2024-09-13 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('publisher_name', models.CharField(max_length=100)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(default='/media/media/book_placeholder.png', upload_to='media/')),
                ('total_rating_value', models.IntegerField(default=0)),
                ('total_rating_count', models.IntegerField(default=0)),
                ('isbn_10', models.CharField(blank=True, max_length=15, verbose_name='ISBN-10')),
                ('edition', models.CharField(blank=True, max_length=100, verbose_name='Edition')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensions')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Weight')),
                ('pages', models.PositiveIntegerField(verbose_name='Number of pages')),
                ('categories', models.ManyToManyField(related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('book', 'author')},
            },
        ),
    ]
