# Generated by Django 4.2.13 on 2024-06-11 03:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0123456789', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long and start with a zero.', regex='^0\\d{9}$')]),
        ),
    ]
