# Generated by Django 4.2.13 on 2024-06-12 09:39

import bookstore_binht.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birthday_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[bookstore_binht.users.models.validate_not_future_date]),
        ),
    ]
