# Generated by Django 4.2.13 on 2024-07-09 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long and start with a zero or region code and 9 numbers of your phone after the first one.', regex='^(0\\d{9}|(\\+\\d{1,3})\\d{9})$')]),
        ),
    ]
