# Generated by Django 4.2.13 on 2024-07-29 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=14, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^(0\\d{9}|(\\+\\d{1,3})\\d{9})$')]),
        ),
    ]
